### ISSUE TITLE
No Fault indication when fault present on Thermocouple

### ISSUE THREAD

**Issue by JasonPittenger** [m5stack/M5Unit-KMeter#1]
I discovered if you request the K-Meter internal temperature when no thermocouple is connected, the result is invalid.
However, it does not let you know that there was an issue.

Looking at the datasheet for the MAX31855, it looks like this condition (as well as shorts to ground or VCC) is detectable and returned with the SPI data.

In M5_KMeter::getTemperature() & getInternalTemp(), the function checks for a fault and returns a value ONLY if there is no fault.
However, it returns the most recent successful value if there is a fault.
This doesn't indicate any issue to the end user.
I do see that the fault information is available with M5_KMeter::getRawData, but the end user has no way of knowing that they need to check this because the fault is not indicated.

Can these functions be modified to return an out of range value in the case of a fault?
Perhaps in the cause of a fault, return the value -999?
As for getInternalTemp(), this should return a valid value regardless of the faults present.

Thanks!

**Comment by lovyan03** [comment]
@JasonPittenger 
Thank you for your patience. Library version v0.1.1 is now available.
Please update the library along with updating the firmware to v1.1.
The specifications have changed significantly in this version, and it is now possible to obtain error status and perform sleep.
See `examples` for specific usage.

**Comment by JasonPittenger** [comment]
Thank you!

Can you clarify usage?
Do I need to call setSleepTime(4) every time before I call sleep(false)?
Or do I need to call setSleepTime(4) one time at power up?
Or do I need to call setSleepTime(4) one time to configure and it will be remembered forever?

**Comment by lovyan03** [comment]
The set values are stored in the unit's NVS and restored at wake-up.
In other words, once it is executed, it does not need to be executed again when the power is turned back on.

**Comment by JasonPittenger** [comment]
Thank you!
I have noticed a significant increase in battery life after this change!
I am running a 4 second sleep time and sampling every 5 seconds.
I'm not 100% what the minimum wake time is, so I give it 1 second to start up.
I have multiple items on the I2C bus, so unfortunately I cant use the wake on SCL low.
However, that is a wonderful feature!

Well done!
