### ISSUE TITLE
are there I2C pullups ?

### ISSUE THREAD

**Issue by ArminPP** [m5stack/M5Unit-KMeter#4]
Can you please tell me if the module uses pull-up resistors on the I2C bus?
I couldn't find any information on the M5Stack website.

I have problems with a M5Atom lite, a I2C M5-hub and 3 slave devices:

- M5Atom lite has no pullups in the schematic (it possibly uses the ESP32 10k internal ones ?)
- M5 K-Meter has 10k pullups according to the schematics
- GY-271 magnetometer probably has 4k7 pullups 
- M5 K-Meter pullups are unknown...

Thank's in advance,
Armin

**Comment by lovyan03** [comment]
Hello, @ArminPP 
The schematic can be found here.

https://static-cdn.m5stack.com/resource/docs/products/unit/kmeter/kmeter_sch_01.webp

It appears to be pulled up with a 10kΩ resistor.

**Comment by ArminPP** [comment]
Thank's a lot !
